version: '3.8'
services:
  db:
    volumes:
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
    env_file:
      - .env
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
    restart: always
    ports:
      - '${MYSQL_PORT}:${MYSQL_PORT}'
  web:
    build: ./api
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      PORT: ${TEST_PORT}
      NODE_ENV: development
    ports:
      - '${TEST_PORT}:${TEST_PORT}'
    depends_on:
      - db
    volumes:
      - ./:/api
    restart: on-failure
