version: '3.8'
services:
  db:
    volumes:
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
    restart: always
    ports:
      - '3306:3306'
  web:
    build: ./web
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
      NODE_ENV: development
    ports:
      - '5001:5001'
    depends_on:
      - db
    restart: on-failure
